[settings]
# Base URLs
BASE_URL=https://jsonplaceholder.typicode.com
UI_BASE_URL=http://books.toscrape.com

# API Endpoints
POSTS_ENDPOINT=/posts
USERS_ENDPOINT=/users
COMMENTS_ENDPOINT=/comments

# Browser Settings
BROWSER=chromium
HEADLESS=True
SLOW_MO=0

# Test Settings
TIMEOUT=30000
ENVIRONMENT=staging